name: pubstore
description: A .
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  hive: ^2.2.1
  json_annotation: ^4.5.0
  logging: ^1.0.2
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.1.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
